[package]
name = "ironcalc_server"
version = "0.5.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5", features = ["json"] }
ironcalc = "0.5"
reqwest = { version = "0.12", features = ["json"] }
roxmltree = "0.21"
serde = "1.0"
serde_json = "1.0"
base64 = "0.22"
